blacklist: []
build_space: build-debug
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Debug
devel_space: devel-debug
extend_path: null
install: false
install_space: install
isolate_devel: false
isolate_install: false
make_args: []
source_space: src
use_internal_make_jobserver: true
whitelist: []
